import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/css/bootstrap-grid.min.css'
import '../styles/bootstrap.min.css'
import Navbar from "@/components/Navbar";
import '../styles/globals.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import UsersPage from "@/app/users/page";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Web Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body>
      <Navbar/>
      <div className="row">
          <div className="col-md-3">
              <UsersPage/>
          </div>
          <div className="col-md-9">
              <div className="container content">{children}</div>
          </div>
      </div>
      </body>
      </html>
  );
}
