import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/css/bootstrap-grid.min.css'
import '../styles/bootstrap.min.css'
import Navbar from "@/components/Navbar";
import '../styles/globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar/>
      <div className="container">{children}</div>
    </html>
  );
}
